config/routes.rb
PhotoFriends::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  
  resources :users do
    resources :groups do
      resources :events
      resources :galleries do
        resources :photos 
        resources :comments
      end
    end
    resources :groupsandusers
  end
  
  resources :sessions

  root 'sessions#new'

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :groups_and_users
  has_many :users, through: :groups_and_users
  has_many :galleries, dependent: :destroy


  
  attr_accessor :password
  
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_uniqueness_of :name
  
  def self.authenticate(name, password)
    group = find_by_name(name)
    if group && group.password_hash == BCrypt::Engine.hash_secret(password, group.password_salt)
      group
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def index
  end
  
  # GET /groups/1
  # GET /groups/1.json
  def show
    @gallery = Gallery.where(group_id: @group.id).to_a
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @groupsandusers = GroupsAndUsers.new(group_id: @group.id, user_id: @user.id)
          if @groupsandusers.save
            format.html { redirect_to user_group_path(@user, @group), notice: 'Group was successfully created.' }
            format.json { render action: 'show', status: :created, location: @group }
          else
            format.html { render action: 'new' }
            format.json { render json: @group.errors, status: :unprocessable_entity }
          end
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to user_group_path(@user, @group), notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    GroupsAndUsers.destroy_all(group_id: @group.id)
    @group.destroy
    set_last_group
    redirect_to user_group_path(@user, @group)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end
    
    def set_user
      @user = User.find(params[:user_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:owner, :name, :password, :password_confirmation, :user_id)
    end

    def set_last_group
      if session[:user_id]
        # user = User.find(session[:user_id])
        # @group = user.groups.order(:updated_at).first
        usergroups = GroupsAndUsers.where(user_id: session[:user_id]).to_a
        groups = []
        if !usergroups.empty?
          usergroups.each do |group|
            groups << Group.find_by(id: group.group_id)
          end
          sorted = groups.sort {|g,h| h[:updated_at] <=> g[:updated_at]}
          @group = Group.find_by(id: sorted[0].id)
        else
          nil
        end
      else
        nil
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  
end

app/views/groups/_form.html.erb
<%= form_for(@group, url: user_groups_path(current_user.id, @group)) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group gray-box col-md-4 col-md-offset-4 form-joingroup">
    <div class="field">
      <%= f.hidden_field :owner, value: current_user.id %>
    </div>
    <div class="field">
      <%= f.text_field :name, class: "form-control", placeholder: "Group Name" %>
    </div>
    <div class="field">
      <%= f.password_field :password, class: "form-control password", placeholder: "Group Password" %>
    </div>
    <div class="field">
      <%= f.password_field :password_confirmation, class: "form-control password-confirm", placeholder:"Confirm Password" %>
    </div>
    <div class="actions">
      <%= f.submit "Save Group", class: "btn btn-primary pull-right" %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="jumbotron">
  <h1>Edit group details</h1>

  <%= form_for(@group, url: user_groups_path(current_user, @group)) do |f| %>
      <% if @group.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

            <ul>
              <% @group.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group gray-box col-md-4 col-md-offset-4 form-joingroup">
        <div class="field">
          <%= f.hidden_field :owner, value: current_user.id %>
        </div>
        <div class="field">
          <%= f.text_field :name, class: "form-control", placeholder: "Group Name" %>
        </div>
        <div class="field">
          <%= f.password_field :password, class: "form-control password", placeholder: "Group Password" %>
        </div>
        <div class="field">
          <%= f.password_field :password_confirmation, class: "form-control password-confirm", placeholder:"Confirm Password" %>
        </div>
        <div class="actions">
          <%= link_to "Delete Group", user_group_path(@user.id, @group.id), method: :delete, class: "btn btn-primary pull-left", data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="actions">
          <%= f.submit "Save Group", class: "btn btn-primary pull-right" %>
        </div>
      </div>
  <% end %>

</div>

<script>
    $(document).ready(function(){
        setbackground("<%= get_background(@group.id) %>");
    });
</script>

app/views/groups/index.html.erb
<div class = "jumbotron" style="overflow:hidden;">
  <h1>You do not belong to any groups!</h1><br />
  <div class="col-md-offset-5 col-md-2 gray-box">
    <%= link_to '<button class = "btn btn-primary pull-left">Create</button>'.html_safe, new_user_group_path %>
    <span style="margin-left: 20px; color: white;">or</span>
    <%= link_to '<button class = "btn btn-primary pull-right">Join</button>'.html_safe, new_user_groupsanduser_path(session[:user_id]) %><br />
  </div>
</div>

<script>
    $(document).ready(function(){
        setbackground("<%= get_background("0") %>");
    });
</script>

app/views/groups/new.html.erb
<div class="jumbotron">
  <h1 class="fancy-header">Create a new group!</h1>
  <h2 class="fancy-sub-header">Create a group of your friends, your family, or whatever you want it to be!</h2>

  <%= render 'form' %>
</div>

<script>
    $(document).ready(function(){
        setbackground("<%= get_background(@group.id) %>");
    });
</script>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <h1 id="group-members" title="<h3 style='margin-top: 8px;'>Group Members</h3>" data-content='<%= get_members(@group.id) %>'><%= @group.name %></h1>
  <% if @gallery.blank? %>
    <h2>You have no galleries!</h2>
    <div class="col-md-3 col-md-offset-5">  
      <%= link_to '<button class="btn pull-left btn-primary">Create</button>'.html_safe, new_user_group_gallery_path(@user, @group) %>
      <p style="text-indent: 10px;">a new one!</p>
    </div>
  <% else %>
    <div class="container visible-md visible-lg">
        <% @gallery.each_slice(3) do |slice| %>
          <div class="row">
              <% slice.each do |g| %>
                <div class="col-md-4 gallery-cont">
                 <div class="gallery">
                    <div class="gallery-header" id="bigtext">
                        <span id="span-<%= g.id %>" class="gallery-title"><%= g.name %></span>
                        <script>$("#span-<%= g.id %>").bigText({ fontSizeFactor:.7 });</script> 
                    </div>
                    <% randomphoto = Photo.where(gallery_id: g.id).take %>
                    <% randomphoto = Photo.new if randomphoto.blank? %>
                    <%= image_tag(randomphoto.image_url(:preview)) %>
                    <div class="btn-group gallery-btns">
                        <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_user_group_gallery_path(@user.id, @group.id, g.id), { class: "btn btn-default btn-lg btn-gall-edit col-md-3", title: "Edit gallery", id: "edit-gal-", 'data-toggle' => "tooltip"} %>
                        <%= link_to "<i class='glyphicon glyphicon-th'></i>".html_safe, user_group_gallery_path(@user, @group, g.id), { class: "btn btn-default btn-lg btn-gall-show col-md-6", title: "View gallery", id: "show-gal-", 'data-toggle' => "tooltip" } %>
                        <%= link_to "<i class='glyphicon glyphicon-picture'></i>".html_safe, new_user_group_gallery_photo_path(@user.id, @group.id, g.id), { class: "btn btn-default btn-lg btn-photo-add col-md-3", title: "Add new photo", id: "add-pic-", 'data-toggle' => "tooltip" } %>
                    </div>
                  </div>
                </div>
              <% end %>
          </div>
        <% end %>
    </div>
    <div class="container visible-sm">
        <% @gallery.each_slice(2) do |slice| %>
          <div class="row">
              <% slice.each do |g| %>
                <div class="col-sm-6 gallery-cont">
                 <div class="gallery">
                    <div class="gallery-header" id="bigtext">
                        <span id="span-<%= g.id %>" class="gallery-title"><%= g.name %></span>
                        <script>$("#span-<%= g.id %>").bigText({ fontSizeFactor:.7 });</script> 
                    </div>
                    <% randomphoto = Photo.where(gallery_id: g.id).take %>
                    <% randomphoto = Photo.new if randomphoto.blank? %>
                    <%= image_tag(randomphoto.image_url(:preview)) %>
                    <div class="btn-group gallery-btns">
                        <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_user_group_gallery_path(@user.id, @group.id, g.id), { class: "btn btn-default btn-lg btn-gall-edit col-sm-3", title: "Edit gallery", id: "edit-gal-", 'data-toggle' => "tooltip"} %>
                        <%= link_to "<i class='glyphicon glyphicon-th'></i>".html_safe, user_group_gallery_path(@user, @group, g.id), { class: "btn btn-default btn-lg btn-gall-show col-sm-6", title: "View gallery", id: "show-gal-", 'data-toggle' => "tooltip" } %>
                        <%= link_to "<i class='glyphicon glyphicon-picture'></i>".html_safe, new_user_group_gallery_photo_path(@user.id, @group.id, g.id), { class: "btn btn-default btn-lg btn-photo-add col-sm-3", title: "Add new photo", id: "add-pic-", 'data-toggle' => "tooltip" } %>
                    </div>
                  </div>
                </div>
              <% end %>
          </div>
        <% end %>
    </div>
    <div class="container visible-xs">
        <% @gallery.each_slice(1) do |slice| %>
          <div class="row">
              <% slice.each do |g| %>
                <div class="col-xs-12 gallery-cont">
                 <div class="gallery">
                    <div class="gallery-header" id="bigtext">
                        <span id="span-<%= g.id %>" class="gallery-title"><%= g.name %></span>
                        <script>$("#span-<%= g.id %>").bigText({ fontSizeFactor:.7 });</script> 
                    </div>
                    <% randomphoto = Photo.where(gallery_id: g.id).take %>
                    <% randomphoto = Photo.new if randomphoto.blank? %>
                    <%= image_tag(randomphoto.image_url(:preview)) %>
                    <div class="btn-group gallery-btns">
                        <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_user_group_gallery_path(@user.id, @group.id, g.id), { class: "btn btn-default btn-lg btn-gall-edit col-xs-3", title: "Edit gallery", id: "edit-gal-", 'data-toggle' => "tooltip"} %>
                        <%= link_to "<i class='glyphicon glyphicon-th'></i>".html_safe, user_group_gallery_path(@user, @group, g.id), { class: "btn btn-default btn-lg btn-gall-show col-xs-6", title: "View gallery", id: "show-gal-", 'data-toggle' => "tooltip" } %>
                        <%= link_to "<i class='glyphicon glyphicon-picture'></i>".html_safe, new_user_group_gallery_photo_path(@user.id, @group.id, g.id), { class: "btn btn-default btn-lg btn-photo-add col-xs-3", title: "Add new photo", id: "add-pic-", 'data-toggle' => "tooltip" } %>
                    </div>
                  </div>
                </div>
              <% end %>
          </div>
        <% end %>
    </div>
  <% end %>
  <div class="btns">
    <%= link_to '<button class="btn pull-right btn-primary">Group Settings</button>'.html_safe, edit_user_group_path(current_user.id, @group) %>
    <%= link_to '<button class="btn pull-right btn-primary btn-spc">New Gallery</button>'.html_safe, new_user_group_gallery_path(@user, @group) %>
  </div>
  </div>

<script>
    $(document).ready(function(){
        setbackground("<%= get_background(@group.id) %>");
        $("[id^=edit-gal-]").tooltip({ trigger: "hover", container: 'body' });
        $("[id^=show-gal-]").tooltip({ trigger: "hover", container: 'body' });
        $("[id^=add-pic-]").tooltip({ trigger: "hover", container: 'body' });
        $('#group-members').popover(poOptions('blueWhite', {
            'placement': 'bottom',
            'html': true,
            'trigger': 'hover',
            'animation': 'true'
        }));
        $('[id^=span-]').bigText();
    });
</script>