config/routes.rb
PhotoFriends::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  
  resources :users do
    resources :groups do
      resources :events
      resources :galleries do
        resources :photos 
        resources :comments
      end
    end
    resources :groupsandusers
  end
  
  resources :sessions

  root 'sessions#new'

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :gallery
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_gallery, :set_group, :set_user

  # GET /photos
  # GET /photos.json
  def index
    @photos = @gallery.photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = @gallery.photos.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = @gallery.photos.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to user_group_gallery_path(@user.id, @group.id, @gallery.id) }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    redirect_to user_group_gallery_photos_path(@user.id, @group.id, @gallery.id)
  end

  # TODO: Don't allow, or add the handling of special characters in comments

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_gallery
      @gallery = Gallery.find(params[:gallery_id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:caption, :image, :gallery_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo, url: user_group_gallery_photo_path(@user, @group, @gallery, @photo)) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="jumbotron">
      <% if request.path == edit_user_group_gallery_photo_path(@user.id, @group.id, @gallery.id, @photo.id) %>
          <h2>Edit photo information</h2>
      <% else %>
          <h1>Upload a new photo</h1>
      <% end %>
      <div class="row">
          <div class="field form-group col-md-6">
              <div class="fileupload fileupload-new" data-provides="fileupload">
                <div class="col-lg-8 col-lg-offset-2">
                  <span class="btn btn-file btn-primary"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><%= f.file_field :image %></span>
                  <div class="fileupload-preview thumbnail upload" style="width: 200px; height: 200px">
                    <%= image_tag(@photo.image, size: "200x200", class: "image") %>
                  </div>

                  <a href="#" class="btn fileupload-exists btn-danger" data-dismiss="fileupload">Remove</a>
                </div>
              </div>
          </div>
          <div class="field col-md-6">
            <%= f.label :caption %><br>
            <%= f.text_field :caption, class: "form-control" %>
          </div>
        </div>
        <div class="field">
        <%= f.hidden_field :gallery, value: @gallery.id %>
        </div>
        <div>
          <p class='alert-danger'>Special characters such as single quotes or double quotes are not allowed in the caption field!!!</p>
        </div>
        <div class="actions">
        <%= f.submit "Save Photo", class: "btn btn-primary pull-right" %>
        </div>
    </div>
<% end %>

<script>
    $(document).ready(function(){
        setbackground("<%= get_background(@group.id) %>");
    });
</script>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="jumbotron">
    <h1>Edit Photo Collection</h1>

    <div id="thumbs">
        <% @photos.each do |photo| %>
          <div id="<%= photo.id %>" class="photo-thumb" onclick="show_photo('<%= photo.id %>', '<%= photo.image_url(:preview) %>', ' <%= photo.caption %>');">
            <img src="<%= photo.image_url(:thumb) %>">
          </div>
        <% end %>
     </div>
</div>
<div id='photo-dialog' data-photoid=''>
  <img id='dialog-photo' src=''>
  <div id='header' class='dialog-header'>
    <h4></h4>
  </div>
  <div id='exit-button' class='exit' data-toggle='tooltip' title='Close Window' onclick="$('#photo-dialog').dialog('close');">
    <img src='/assets/Button-Close-icon.png'>
  </div>
  <div id='delete-button' class='delete' data-toggle='tooltip' title='Delete Photo' onclick="delete_photo('<%= @user.id %>', '<%= @group.id %>', '<%= @gallery.id %>');">
    <img src='/assets/DeleteRed.png'>
  </div>
</div>
<script>
    $(document).ready(function(){
        setbackground("<%= get_background(@group.id) %>");
        $('#photo-dialog').dialog({
            autoOpen: false,
            height: 'auto',
            width: 'auto',
            modal: true
        }).dialog("widget").find(".ui-dialog-title").hide();
        $('#exit-button').tooltip({ trigger: "hover", container: 'body' });
        $('#delete-button').tooltip({ trigger: "hover", container: 'body' });
    });
</script>

app/views/photos/new.html.erb
<%= render 'form' %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= @photo.caption %>
</p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Path:</strong>
  <%= @photo.path %>
</p>

<p>
  <strong>Gallery:</strong>
  <%= @photo.gallery %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>