config/routes.rb
PhotoFriends::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  
  resources :users do
    resources :groups do
      resources :events
      resources :galleries do
        resources :photos 
        resources :comments
      end
    end
    resources :groupsandusers
  end
  
  resources :sessions

  root 'sessions#new'

  

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :group
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
  before_action :set_group, :set_user
  
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @photos = Photo.where(gallery_id: @gallery.id).order("created_at ASC").to_a
    @comments = Comment.where(gallery_id: @gallery.id).to_a
    @comment = Comment.new
  end

  # GET /galleries/new
  def new
    @gallery = @group.galleries.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = @group.galleries.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to user_group_path(@user, @group) }
        format.json { render action: 'show', status: :created, location: @gallery }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to user_group_gallery_path(@user, @group, @gallery) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_path(@user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end
    
    def set_group
      @group = Group.find(params[:group_id])
    end
    
    def set_user
      @user = User.find(params[:user_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :archive, :group_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper

end

app/views/galleries/_form.html.erb
<div class="jumbotron">
    <% if request.path == edit_user_group_gallery_path(@user.id, @group.id, @gallery.id) %>
        <h2>Edit gallery information</h2>
    <% else %>
        <h2>Create a new gallery</h2>
    <% end %>
    <%= form_for(@gallery, url: user_group_galleries_path(@user, @group)) do |f| %>
      <% if @gallery.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

          <ul>
          <% @gallery.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group gray-box col-md-4 col-md-offset-4">
          <div class="field">
            <%= f.text_field :name, class: "form-control", placeholder: "Gallery Name" %>
          </div>
          <div class="field">
            <%= f.hidden_field :group, value: @group.id %><br />
          </div>
          <div class="actions">
            <%= f.submit "Save Gallery", class: "btn btn-primary pull-right" %>
          </div>
      </div>
    <% end %>
</div>

<<script>
    $(document).ready(function(){
        setbackground("<%= get_background(@group.id) %>");
    });
</script>

app/views/galleries/edit.html.erb
<div class="jumbotron">
  <% if request.path == edit_user_group_gallery_path(@user.id, @group.id, @gallery.id) %>
      <h2>Edit gallery information</h2>
  <% else %>
      <h2>Create a new gallery</h2>
  <% end %>
  <%= form_for(@gallery, url: user_group_gallery_path(@user, @group, @gallery.id)) do |f| %>
      <% if @gallery.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

            <ul>
              <% @gallery.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-group gray-box col-md-4 col-md-offset-4">
        <div class="field">
          <%= f.text_field :name, class: "form-control", placeholder: "Gallery Name" %>
        </div>
        <div class="field">
          <%= f.hidden_field :group, value: @group.id %><br />
        </div>
        <div class="actions">
          <%= link_to "Remove Gallery", user_group_gallery_path(@user.id, @group.id, @gallery.id), method: :delete, class: "btn btn-primary pull-left", data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="actions">
          <%= f.submit "Save Gallery", class: "btn btn-primary pull-right" %>
        </div>
      </div>
  <% end %>
</div>

<script>
    $(document).ready(function(){
        setbackground("<%= get_background(@group.id) %>");
    });
</script>

app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Archive</th>
      <th>Group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.name %></td>
        <td><%= gallery.archive %></td>
        <td><%= gallery.group %></td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/show.html.erb
<div class="jumbotron">
  <h1 class="gallery-header"><%= @gallery.name %></h1>
  <div id="blueimp-gallery-carousel" class="blueimp-gallery blueimp-gallery-carousel blueimp-gallery-controls blueimp-gallery-display">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
  </div>
  <% if @photos.blank? %>
    <h2>You have no photos!</h2><br />
    <%= link_to "<button class='btn btn-primary col-md-2 col-md-offset-5'>Add Photo</button>".html_safe, new_user_group_gallery_photo_path(@user.id, @group.id, @gallery.id) %>
  <% else %>
    <div id="links" class="links">
        <% @photos.each do |photo| %>
          <a href='<%= photo.image_url(:large) %>' title='<%= photo.caption %>'>
          </a>
        <% end %>
    </div>
  <% end %>
  <div class="btn-group col-md-offset-3 col-md-6 gall-btns">
    <%= link_to 'Add Photo', new_user_group_gallery_photo_path(@user.id, @group.id, @gallery.id), class: "btn btn-primary col-md-4" %>
    <%= link_to 'Edit Photo Collection', user_group_gallery_photos_path(@user, @group, @gallery), class: "btn btn-primary col-md-4" %>
    <%= link_to 'Back to Galleries', user_group_path(@user, @group), class: "btn btn-primary col-md-4" %>
  </div>
  <br />
  <div class="comment-section">
      <% @comments.each do |comment| %>
        <div class="comment pull-right" id="comment-<%= comment.id %>">
          <script>set_comment_back('comment-<%= comment.id %>');</script>
          <%= image_tag(comment.user.avatar, size: "80x80", class: "img-circle pull-left") %>
          <div class="comment-panel pull-left">
              <p class="comment-time pull-right">
                <%= comment.updated_at.strftime("%B %-d, %Y") %>
              </p>
              <p class="comment-time pull-right tiny">
                <%= comment.updated_at.strftime("%l:%M %p") %>
              </p>
              <p class="comment-username pull-right">
                <%= comment.user.username.capitalize %><span class="tiny">said</span>
              </p>
          </div>
          <p class="comment-text pull-left">
            <%= comment.text %>
          </p>
        </div>
      <% end %>
  </div>
  <% if @comments.blank? %>
    <button id="no-comm" class="col-md-4 col-md-offset-4 alert-danger" onclick="show_comment();">No comments yet. Why not make one?</button>
  <% else %>
      <button id="show_new_comment" class="btn btn-sm btn-primary col-md-2 col-md-offset-5" onclick="show_comment();">New Comment</button>
  <% end %>

  <div class="">
    <div class="new-comment form-inline pull-right" id="new-comment" style="visibility: hidden;" role="form">
      <script>set_comment_back('new-comment');</script>
      <%= form_for(@comment, url: user_group_gallery_comments_path(@user, @group, @gallery)) do |f| %>
          <%= f.hidden_field :group_id, value: @group.id %>
          <%= f.hidden_field :user_id, value: @user.id %>
          <div class="form-group pull-left">
            <%= image_tag(@user.avatar, size: "80x80", class: "img-circle") %>
          </div>
          <div class="comment-panel pull-left">
            <p class="comment-time pull-right">
              Say something
            </p>
            <p class="comment-username pull-right">
              <%= @user.username.capitalize %>
            </p>
          </div>
          <div class="form-group">
            <%= f.text_area :text, class: "form-control pull-left", size: "80x3" %>
          </div>
          <div class="form-group">
            <%= f.submit "Save", class: "btn btn-primary btn-sm pull-left" %>
          </div>
      <% end %>
    </div> <br />
  </div>
  <br />
</div>

<script src="/assets/blueimp/blueimp-gallery.min.js"></script>
<script>
    $(document).ready(function(){
        setbackground("<%= get_background(@group.id) %>");
        init_gallery();
    });
</script>