config/routes.rb
PhotoFriends::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_in" => "sessions#new", :as => "sign_in"
  
  resources :users do
    resources :groups do
      resources :events
      resources :galleries do
        resources :photos 
        resources :comments
      end
    end
    resources :groupsandusers
  end
  
  resources :sessions

  root 'sessions#new'

  

end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="/">Photo Friends</a>
  </div>

  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Groups <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% @allgroups = get_all_groups %>
            <% if @allgroups == nil %> 
              <li><a href="#"><span class="text-muted">No Groups</span></a></li> 
            <% else %>
              <% @allgroups.each do |group| %>
                <li><%= link_to "#{group.name}", user_group_path(current_user.id, group.id) %></li>
              <% end %>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "Create Group", new_user_group_path(current_user) %></li>
            <li><%= link_to "Join Group", new_user_groupsanduser_path(current_user) %></li>
          </ul>
        </li>
    </ul>
    
    <div class="col-md-offset-5">
      <ul class="nav navbar-nav navbar-left">
        <li class="navbar-brand"><%= current_user.name %></li>
      </ul>
    </div>
    
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", edit_user_path(current_user) %></li>
            <!-- <li><a href="#">Settings</a></li> -->
            <li class="divider"></li>
            <li><a href="/log_out">Log Out</a></li>
            <% if current_user.userlevel == 0 %>
              <li class="divider"></li>
              <li><%= link_to "Admin Page", user_path(current_user) %></li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo Friends</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% if session[:user_id] %>
  <%= render 'layouts/navbar' %>
<% end %>
  
<%= yield %>
<br />
<div class="debug-div">
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>